# KNN_HEART_DISEASES

In [531]:
import pandas as pd

In [532]:
df=pd.read_csv(r"C:\Users\vv\Downloads\heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [533]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [534]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [535]:
df['HeartDisease'] = df['HeartDisease'].map({1: 'yes', 0: 'no'})
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,no
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,yes
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,no
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,yes
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,no
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,yes
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,yes
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,yes
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,yes
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,no

In [536]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,no
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,yes
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,no
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,yes
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,no
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,yes
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,yes
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,yes
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,yes
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,no

In [537]:
# df['HeartDisease'] = df['HeartDisease'].apply(lambda x: 'yes' if x == 1 else 'no')
# df

In [538]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, LabelEncoder


label_encoders = {}
categorical_columns = ['Sex','ChestPainType','ExerciseAngina','ST_Slope','RestingECG']	

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [539]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,no
1,49,0,2,160,180,0,1,156,0,1.0,1,yes
2,37,1,1,130,283,0,2,98,0,0.0,2,no
3,48,0,0,138,214,0,1,108,1,1.5,1,yes
4,54,1,2,150,195,0,1,122,0,0.0,2,no
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,yes
914,68,1,0,144,193,1,1,141,0,3.4,1,yes
915,57,1,0,130,131,0,1,115,1,1.2,1,yes
916,57,0,1,130,236,0,0,174,0,0.0,1,yes
917,38,1,2,138,175,0,1,173,0,0.0,2,no

In [590]:
x=df[['Age','Sex','ChestPainType','RestingBP','Cholesterol','FastingBS','RestingECG','MaxHR','ExerciseAngina','Oldpeak','ST_Slope']]
y=df[['HeartDisease']]

x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [591]:
y

    HeartDisease
0             no
1            yes
2             no
3            yes
4             no
..           ...
913          yes
914          yes
915          yes
916          yes
917           no

[918 rows x 1 columns]

In [592]:
import numpy as np

In [593]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=30)

y_test

    HeartDisease
771          yes
132          yes
609          yes
273           no
373          yes
..           ...
367          yes
596          yes
338          yes
71            no
353          yes

[92 rows x 1 columns]

In [594]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [595]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

knn.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [596]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)

In [597]:
pred=knn.predict(x_test)
pred

array(['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no',
       'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes',
       'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes',
       'yes', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no',
       'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'no', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'no',
       'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'no', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes',
       'no', 'yes'], dtype=object)

In [598]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

results=confusion_matrix(y_test,pred)
print('confusion matrix')
print(results)
print('Accuracy score:', accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

confusion matrix
[[28 19]
 [ 9 36]]
Accuracy score: 0.6956521739130435
              precision    recall  f1-score   support

          no       0.76      0.60      0.67        47
         yes       0.65      0.80      0.72        45

    accuracy                           0.70        92
   macro avg       0.71      0.70      0.69        92
weighted avg       0.71      0.70      0.69        92

In [599]:
import numpy as np

In [600]:
k1=np.array([[37,	1,	1,	130,	283,	0,	2,	98,	0,	0.0,	2	]])
k1

array([[ 37.,   1.,   1., 130., 283.,   0.,   2.,  98.,   0.,   0.,   2.]])

In [601]:
pred=knn.predict(k1)
pred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['no'], dtype=object)

In [602]:
k2=np.array([[57,	0,	1,	130,	236,	0,	0,	174,	0,	0.0,	1]])
k2

array([[ 57.,   0.,   1., 130., 236.,   0.,   0., 174.,   0.,   0.,   1.]])

In [603]:
pred=knn.predict(k2)
pred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['yes'], dtype=object)