# NAIVE_BAYES_SENTIMENT_ANALYSIS(MOVIE_REVIEWS)

In [63]:
import pandas as pd
import nltk

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report


import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

In [64]:
import pandas as pd

In [65]:
df=pd.read_csv(r"C:\Users\vv\Downloads\IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [66]:
import re

def clean(text):
    text = str(text).lower()
    # Corrected: Added missing =, added closing bracket in regex, and closed the quote
    text = re.sub(r'\[.*?\]', '', text)
    # Corrected: Fixed extra comma and properly formatted the substitution
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # Corrected: Properly closed the re.sub call
    text = re.sub(r'<.*?>+', '', text)
    return text

In [67]:
df['review']=df['review'].apply(clean)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [68]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['sentiment']=encoder.fit_transform(df.sentiment)

In [69]:
x=df.iloc[0:,0]
x

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [70]:
y=df.iloc[0:,1]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [71]:
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\vv\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vv\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [72]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [73]:

# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

In [74]:

# Text preprocessing function
def preprocess_text(text):
    # Handle missing values
    text = str(text)

    # Lowercase and tokenize
    tokens = word_tokenize(text.lower())

    # Lemmatize
    lemmatized_tokens = [lemmatizer.lemmatize(token)for token in tokens]

    # Join back into a string
    return ' '.join(lemmatized_tokens)

In [91]:
# PREPROCESS TEXT FIRST

df['processed_review'] = df['review'].apply(preprocess_text)
df['processed_review']

0        one of the other reviewer ha mentioned that af...
1        a wonderful little production . the filming te...
2        i thought this wa a wonderful way to spend tim...
3        basically there 's a family where a little boy...
4        petter mattei 's `` love in the time of money ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot , bad dialogue , bad acting , idiotic...
49997    i am a catholic taught in parochial elementary...
49998    i 'm going to have to disagree with the previo...
49999    no one expects the star trek movie to be high ...
Name: processed_review, Length: 50000, dtype: object

In [76]:
# TF-IDF VECTORIZATION

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['processed_review'])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6640661 stored elements and shape (50000, 97371)>

In [77]:
# TRAIN TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [78]:
# MODEL TRAINING

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [79]:
# PREDICTION

y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, ..., 0, 0, 0], shape=(10000,))

In [80]:
# EVALUATION
# ==========================

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.862

Classification Report:

              precision    recall  f1-score   support

           0       0.84      0.89      0.86      4961
           1       0.88      0.84      0.86      5039

    accuracy                           0.86     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000

In [89]:
# New review from user
review = input("Enter a review: ")

# Preprocess
review_processed = preprocess_text(review)

# Convert to TF-IDF features
review_vector = tfidf.transform([review_processed])

# Predict
prediction = model.predict(review_vector)[0]

# Display result
if prediction == 1:
    print("Positive Review 😊")
else:
    print("Negative Review 😞")

Enter a review:  A wonderful little production.The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and  sometimes discomforting, sense of realism to the entire piece.The actors are extremely well chosen- Michael Sheen not only has got all  the polari but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams diary entries,  not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master s of  comedy and his life.The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional dream techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and  Halliwell and the sets (particularly of their flat with Halliwells murals decorating every surface) are terribly well done

Positive Review 😊

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

# # Re-fit the encoder on your original target labels
# encoder = LabelEncoder()
# encoder.fit(y)  # Replace 'y' with your original target array/column

# Now your code will work
t3 = """A wonderful little production.The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and 
sometimes discomforting, sense of realism to the entire piece.The actors are extremely well chosen- Michael Sheen not only has got all 
the polari but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams diary entries, 
not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master s of 
comedy and his life.The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional
dream techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and 
Halliwell and the sets (particularly of their flat with Halliwells murals decorating every surface) are terribly well done"""
text1 = tfidf.transform([t3])
prd = model.predict(text1)
original = encoder.inverse_transform(prd)
original[0]
print("negative😞" if prd[0] == 0 else "positive😊")

positive😊